#!/usr/bin/env node
/**
 * Build the browser engines served by the platform tools.
 *
 *   node scripts/build-engines.mjs        (also runs as part of `npm run build`)
 *
 * For each src/engines/src/<platform>.js: inline the /*@include shared/x.js*\/ files,
 * parse-check it (a broken engine never ships: applix lost a run to one that did not
 * parse), minify it (fewer tokens for Claude to paste), and version it by content hash.
 * Also emits the shared resolver on its own (RESOLVER_SOURCE), so resolve_answers on the
 * server answers exactly as the engines do. Writes src/engines/generated.ts, which is
 * committed so the Vercel function needs no build step of its own.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { transform } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "src/engines/src");
const PLACEHOLDER = "__AUPPLY_CFG__";

const inline = (code) =>
  code.replace(/\/\*@include (shared\/[a-z]+\.js)\*\//g, (_, file) => readFileSync(join(srcDir, file), "utf8"));

const engines = {};
for (const file of readdirSync(srcDir).filter((f) => f.endsWith(".js")).sort()) {
  const platform = file.replace(/\.js$/, "");
  const full = inline(readFileSync(join(srcDir, file), "utf8"));
  new vm.Script(full, { filename: file });
  const { code } = await transform(full, { minify: true, target: "chrome100", charset: "ascii", legalComments: "none" });
  const source = code.trim();
  new vm.Script(source, { filename: `${file} (minified)` });
  if (source.split(PLACEHOLDER).length !== 2) throw new Error(`${file}: expected exactly one ${PLACEHOLDER}`);
  const version = createHash("sha256").update(source).digest("hex").slice(0, 10);
  engines[platform] = { version, source };
  console.log(`${platform.padEnd(10)} ${version}  ${(full.length / 1024).toFixed(1)}KB -> ${(source.length / 1024).toFixed(1)}KB`);
}

const resolverSource = ["shared/core.js", "shared/resolver.js"].map((f) => readFileSync(join(srcDir, f), "utf8")).join("\n");
new vm.Script(resolverSource, { filename: "resolver" });

const body = Object.entries(engines)
  .map(([p, e]) => `  ${p}: {\n    version: ${JSON.stringify(e.version)},\n    source: ${JSON.stringify(e.source)},\n  },`)
  .join("\n");
writeFileSync(
  join(root, "src/engines/generated.ts"),
  `// Generated by scripts/build-engines.mjs from src/engines/src. Do not edit by hand.\n` +
    `export const ENGINES = {\n${body}\n} as const;\n\nexport const CFG_PLACEHOLDER = ${JSON.stringify(PLACEHOLDER)};\n\n` +
    `/** shared/core.js + shared/resolver.js, evaluated server-side by src/platforms/resolver.ts. */\n` +
    `export const RESOLVER_SOURCE = ${JSON.stringify(resolverSource)};\n`
);
